Rails.application.routes.draw do
  get 'hope/index'
  get 'money/bank_statement' => 'money#bank_statement'
  get 'money/shopping_history' => 'money#shopping_history'
  get 'money/collection' => 'money#collection'
  post 'money/new' => 'money#new'
  get 'money/new' => 'money#new'
  post 'money/create' => 'money#create'
  post 'money/claim' => 'money#claim'
  get 'money/claim' => 'money#claim'
  post 'money/claim_create' => 'money#claim_create'
  post 'money/:id/collect_create' => 'money#collect_create'
  get 'money/:id/edit' => 'money#edit'
  post 'money/:id/edit' => 'money#edit'
  post 'money/:id/update' => 'money#update'
  get 'money/:id/history' => 'money#history'
  post 'money/:id/history_fixed' => 'money#history_fixed'
  post 'money/:id/history_update' => 'money#history_update'
  post 'money/:id/collect' => 'money#collect'
  post 'money/:id/client' => 'money#client'

  
  get 'menu/index'
  get 'admin/login' => 'admin#login_form'
  get 'user/info' => 'user#user_info'
  post 'user/new' => 'user#new'
  get 'user/new' => 'user#new'
  post 'user/create' => 'user#create'
  post 'user/:id/edit' => 'user#edit'
  post 'user/:id/update' => 'user#update'
  post 'user/:id/destroy' => 'user#destroy'

  get 'hope/index' => 'hope#index'
  post 'hope/new' => 'hope#new'
  post 'hope/:id/edit' => 'hope#edit'
  post 'hope/create' => 'hope#create'
  post 'hope/:id/update' => 'hope#update'
  post 'hope/:id/destroy' => 'hope#destroy'

  post 'admin/login' => 'admin#login'
  post 'admin/logout' => 'admin#logout'
  get 'admin/index' => 'admin#admin_user_index'
  post 'admin/new' => 'admin#new'
  post 'admin/create' => 'admin#create'
  post 'admin/:id/edit' => 'admin#edit'
  post 'admin/:id/update' => 'admin#update'

  get '/' => 'admin#login_form'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
